"""Build the stage-7 figure report as Word documents — in English, Chinese, or both.

Demonstrates the selectable output language of report_docx.build_report. By default it
writes all three (Figure_Report.docx = bilingual, plus _EN and _ZH); set the env var
PAPERFIG_LANG to "en" | "zh" | "bilingual" to write just one.

Each item carries {"en":.., "zh":..} text so any language renders cleanly.
"""
import os
from _common import FIGDIR  # noqa: F401  (adds skill scripts to sys.path)
from report_docx import build_report

EXAMPLE_DIR = FIGDIR.parent

meta = [
    ({"en": "Source paper", "zh": "来源论文"},
     {"en": "Chicco & Jurman (2020), BMC Med Inform Decis Mak 20:16 (CC BY 4.0)",
      "zh": "Chicco & Jurman (2020),BMC Med Inform Decis Mak 20:16(CC BY 4.0)"}),
    ({"en": "Data", "zh": "数据"},
     {"en": "UCI dataset 519 (CC BY 4.0); 299 patients, 96 deaths (32%), median follow-up 115 d",
      "zh": "UCI 数据集 519(CC BY 4.0);299 例患者,96 例死亡(32%),随访中位 115 天"}),
    ({"en": "Preset", "zh": "预设"}, {"en": "generic high-quality", "zh": "generic 高质量预设"}),
    ({"en": "Generated by", "zh": "生成"},
     {"en": "paper-figures skill — lifelines / scikit-learn, seed = 0",
      "zh": "paper-figures 技能 — lifelines / scikit-learn,种子 = 0"}),
]

items = [
    {"kind": "figure", "number": "1", "image": "figures/Fig1.png", "width_in": 6.3,
     "title": {"en": "Cohort overview", "zh": "队列概览"},
     "claim": {"en": "Deaths accrue over variable follow-up → survival analysis is required.",
               "zh": "事件在长短不一的随访期内发生 → 需采用生存分析。"},
     "caption": {
        "en": "Figure 1. Study cohort (n=299; 96 deaths). (A) Age distribution by outcome. (B) Follow-up time by "
              "outcome (box = median + IQR; points = patients). Variable follow-up motivates time-to-event analysis.",
        "zh": "图 1。研究队列(n=299;96 例死亡)。(A)年龄分布按结局。(B)随访时间按结局(箱体=中位数+四分位距,"
              "散点=患者)。随访长短不一,故采用时间-事件分析。"},
     "annotations": {
        "en": [("A", "overlaid histograms"), ("B", "box + points"), ("Color", "blue = survived, orange = died")],
        "zh": [("A", "叠加直方图"), ("B", "箱线+散点"), ("颜色", "蓝=生存,橙=死亡")]},
     "citation": {"en": "Methods/Results, cohort: \"Of 299 patients, 96 (32%) died over a median 115-day follow-up (Fig. 1).\"",
                  "zh": "方法/结果,队列描述:\"299 例中 96 例(32%)在中位 115 天随访内死亡(图 1)。\""},
     "repro": "scripts/make_fig1_cohort_overview.py"},

    {"kind": "figure", "number": "2", "image": "figures/Fig2.png", "width_in": 4.2,
     "title": {"en": "Survival by ejection fraction (Kaplan–Meier)", "zh": "按射血分数的生存(Kaplan–Meier)"},
     "claim": {"en": "Patients with reduced ejection fraction have markedly worse survival.",
               "zh": "射血分数降低的患者生存明显更差。"},
     "caption": {
        "en": "Figure 2. Kaplan–Meier survival by ejection-fraction category — reduced (<30%, n=59), mid (30–45%, "
              "n=160), preserved (≥45%, n=80) — with 95% bands and numbers at risk/censored/events. Log-rank p<0.001.",
        "zh": "图 2。按射血分数分组的 Kaplan–Meier 生存曲线——降低(<30%,n=59)、中间(30–45%,n=160)、保留"
              "(≥45%,n=80)——含 95% 置信带及风险/删失/事件数。log-rank p<0.001。"},
     "annotations": {
        "en": [("Groups", "clinically defined EF strata"), ("Below plot", "at-risk / censored / events table"),
               ("Test", "3-group log-rank")],
        "zh": [("分组", "按临床界值划分的 EF 分层"), ("图下方", "风险/删失/事件数表"), ("检验", "3 组 log-rank")]},
     "citation": {"en": "Results, survival: \"Reduced ejection fraction was associated with lower survival (Fig. 2).\"",
                  "zh": "结果,生存:\"射血分数降低与生存率下降相关(图 2)。\""},
     "repro": "scripts/make_fig2_kaplan_meier.py"},

    {"kind": "figure", "number": "3", "image": "figures/Fig3.png", "width_in": 6.3,
     "title": {"en": "Key predictors by outcome", "zh": "关键预测因子按结局"},
     "claim": {"en": "The deceased had lower ejection fraction and higher serum creatinine.",
               "zh": "死亡者射血分数更低、血清肌酐更高。"},
     "caption": {
        "en": "Figure 3. The two headline predictors by outcome. (A) Ejection fraction and (B) serum creatinine in "
              "patients who survived vs died. Box = median + IQR; points = patients. Mann–Whitney U; ***p<0.001.",
        "zh": "图 3。两个核心预测因子按结局。(A)射血分数、(B)血清肌酐,生存者与死亡者对比。箱体=中位数+四分位距,"
              "散点=患者。Mann–Whitney U;***p<0.001。"},
     "annotations": {
        "en": [("Test", "Mann–Whitney U (creatinine right-skewed)"), ("Markers", "***p<0.001")],
        "zh": [("检验", "Mann–Whitney U(肌酐右偏)"), ("标记", "***p<0.001")]},
     "citation": {"en": "Results, univariable: \"EF was lower and creatinine higher among those who died (Fig. 3; Table 1).\"",
                  "zh": "结果,单因素:\"死亡者射血分数更低、肌酐更高(图 3;表 1)。\""},
     "repro": "scripts/make_fig3_predictors_boxplot.py"},

    {"kind": "figure", "number": "4", "image": "figures/Fig4.png", "width_in": 4.5,
     "title": {"en": "Multivariable Cox model (forest)", "zh": "多因素 Cox 模型(森林图)"},
     "claim": {"en": "Age, low EF and high creatinine independently raise mortality hazard.",
               "zh": "年龄、低射血分数与高肌酐独立升高死亡风险。"},
     "caption": {
        "en": "Figure 4. Hazard ratios (95% CI) from a multivariable Cox model (log scale; reference HR=1). "
              "Continuous predictors standardized (HR per 1 SD); coloured = p<0.05. Age (1.74), creatinine (1.39), "
              "CPK (1.24), anaemia (1.58), hypertension (1.61) raised hazard; ejection fraction (0.56) lowered it. "
              "Concordance index = 0.74.",
        "zh": "图 4。多因素 Cox 模型的风险比(95% CI;对数坐标,参考 HR=1)。连续变量标准化(HR 为每 1 SD);彩色为 "
              "p<0.05。年龄(1.74)、肌酐(1.39)、CPK(1.24)、贫血(1.58)、高血压(1.61)升高风险;射血分数(0.56)"
              "降低风险。一致性指数=0.74。"},
     "annotations": {
        "en": [("Scale", "log-scale HR, reference at 1"), ("Continuous", "standardized → per 1 SD"),
               ("Highlight", "significant predictors coloured")],
        "zh": [("坐标", "对数 HR,参考线在 1"), ("连续变量", "标准化 → 每 1 SD"), ("高亮", "显著预测因子着色")]},
     "citation": {"en": "Results, adjusted analysis: \"EF, creatinine and age were independent predictors (Fig. 4; Table 2).\"",
                  "zh": "结果,校正分析:\"射血分数、肌酐与年龄为独立预测因子(图 4;表 2)。\""},
     "repro": "scripts/make_fig4_cox_forest.py"},

    {"kind": "figure", "number": "5", "image": "figures/Fig5.png", "width_in": 4.2,
     "title": {"en": "Correlations among predictors", "zh": "预测因子间相关"},
     "claim": {"en": "Predictors are weakly correlated — little collinearity.",
               "zh": "预测因子相关较弱——共线性低。"},
     "caption": {
        "en": "Figure 5. Spearman correlations among continuous variables (diverging colormap centred at ρ=0; ρ "
              "annotated). Correlations are weak (|ρ|≤0.30), arguing against collinearity in the Cox model.",
        "zh": "图 5。连续变量间的 Spearman 相关(发散色标以 ρ=0 为中心,标注 ρ)。相关普遍较弱(|ρ|≤0.30),"
              "表明 Cox 模型无明显共线性。"},
     "annotations": {
        "en": [("Method", "Spearman (robust to skew)"), ("Colormap", "diverging, centred at 0")],
        "zh": [("方法", "Spearman(抗偏态)"), ("色标", "发散,居中于 0")]},
     "citation": {"en": "Results, diagnostics: \"Predictors were weakly correlated, arguing against collinearity (Fig. 5).\"",
                  "zh": "结果,模型诊断:\"预测因子相关较弱,提示无共线性(图 5)。\""},
     "repro": "scripts/make_fig5_correlation.py"},

    {"kind": "figure", "number": "6", "image": "figures/Fig6.png", "width_in": 4.2,
     "title": {"en": "Two features vs full set (ROC)", "zh": "两特征 vs 全特征(ROC)"},
     "claim": {"en": "Serum creatinine + ejection fraction predict death almost as well as all features.",
               "zh": "血清肌酐+射血分数预测死亡几乎与全部特征一样好。"},
     "caption": {
        "en": "Figure 6. ROC for predicting in-study death (logistic regression, 5-fold cross-validated). A "
              "two-feature model — creatinine + ejection fraction (AUC=0.75) — nearly matched the full model "
              "(AUC=0.76). Follow-up time excluded to avoid leakage.",
        "zh": "图 6。预测院内死亡的 ROC(Logistic 回归,5 折交叉验证)。仅用肌酐+射血分数(AUC=0.75)几乎与全特征"
              "模型(AUC=0.76)持平。已排除随访时间以防泄漏。"},
     "annotations": {
        "en": [("Validation", "cross-validated AUC, not in-sample"), ("Leakage", "`time` excluded as predictor"),
               ("Diagonal", "chance line shown")],
        "zh": [("验证", "交叉验证 AUC,非样本内"), ("防泄漏", "排除 `time` 作为预测因子"), ("对角线", "随机参考线")]},
     "citation": {"en": "Discussion, parsimony: \"Two features reproduced most of the full model's discrimination (Fig. 6).\"",
                  "zh": "讨论,简约性:\"两个特征再现了全模型的大部分判别力(图 6)。\""},
     "repro": "scripts/make_fig6_roc.py"},

    {"kind": "table", "number": "1", "csv": "figures/Table1.csv",
     "title": {"en": "Baseline characteristics", "zh": "基线特征"},
     "table_title": {"en": "Table 1. Baseline characteristics by survival status.",
                     "zh": "表 1。按生存状态的基线特征。"},
     "table_note": {"en": "Continuous: median [IQR], Mann–Whitney U; binary: n (%), chi-square. Data: Chicco & Jurman (2020).",
                    "zh": "连续变量:中位数 [四分位距],Mann–Whitney U;二分类:n (%),卡方检验。数据:Chicco & Jurman (2020)。"},
     "claim": {"en": "Cohort description and univariable differences.", "zh": "队列描述与单因素差异。"},
     "annotations": {
        "en": [("Continuous", "median [IQR]"), ("Binary", "n (%)"), ("p", "univariable, unadjusted for follow-up")],
        "zh": [("连续变量", "中位数 [四分位距]"), ("二分类", "n (%)"), ("p", "单因素,未校正随访时间")]},
     "citation": {"en": "Results, opening: \"Baseline characteristics are summarized in Table 1.\"",
                  "zh": "结果,开头:\"基线特征汇总于表 1。\""},
     "repro": "scripts/make_table1_baseline.py"},

    {"kind": "table", "number": "2", "csv": "figures/Table2.csv",
     "title": {"en": "Multivariable Cox model", "zh": "多因素 Cox 模型"},
     "table_title": {"en": "Table 2. Multivariable Cox proportional-hazards model for mortality.",
                     "zh": "表 2。死亡的多因素 Cox 比例风险模型。"},
     "table_note": {"en": "HR with 95% CI; continuous predictors standardized (per 1 SD). C-index = 0.74; n=299, events=96. "
                          "Data: Chicco & Jurman (2020).",
                    "zh": "HR 及 95% CI;连续变量标准化(每 1 SD)。一致性指数=0.74;n=299,事件=96。数据:Chicco & Jurman (2020)。"},
     "claim": {"en": "Exact adjusted hazard ratios behind Fig. 4.", "zh": "图 4 背后的精确校正风险比。"},
     "annotations": {
        "en": [("Model", "all covariates jointly"), ("Continuous", "per 1 SD"), ("Fit", "C-index reported")],
        "zh": [("模型", "全部协变量同时纳入"), ("连续变量", "每 1 SD"), ("拟合", "报告 C-index")]},
     "citation": {"en": "Results, adjusted analysis: exact HRs cited alongside Fig. 4.",
                  "zh": "结果,校正分析:精确 HR 与图 4 并列引用。"},
     "repro": "scripts/make_table2_cox.py"},
]

title = {"en": "Figure & Table Report", "zh": "图表报告"}
subtitle = {"en": "Heart-failure survival — paper-figures worked example",
            "zh": "心衰生存分析 — paper-figures 案例"}

LANG = os.environ.get("PAPERFIG_LANG", "all")
targets = {"bilingual": "Figure_Report.docx", "en": "Figure_Report_EN.docx", "zh": "Figure_Report_ZH.docx"}
to_make = targets if LANG == "all" else {LANG: targets[LANG]}
for lang, fname in to_make.items():
    out = EXAMPLE_DIR / fname
    build_report(out, title=title, subtitle=subtitle, meta=meta, items=items,
                 base_dir=str(EXAMPLE_DIR), lang=lang)
    print(f"wrote {out}  (lang={lang})")
