"""Build the stage-7 figure report as a Word document (Figure_Report.docx).

Embeds every figure image and renders the tables inline as three-line tables, with
bilingual captions, annotations, citation locations and reproducibility notes.
"""
from _common import FIGDIR  # noqa: F401  (adds skill scripts to sys.path)
from report_docx import build_report

EXAMPLE_DIR = FIGDIR.parent

meta = [
    ("Source paper / 来源论文", "Chicco & Jurman (2020), BMC Med Inform Decis Mak 20:16 (CC BY 4.0)"),
    ("Data / 数据", "UCI dataset 519 (CC BY 4.0); 299 patients, 96 deaths (32%), median follow-up 115 d"),
    ("Preset / 预设", "generic high-quality (single/double column)"),
    ("Generated by / 生成", "paper-figures skill — lifelines / scikit-learn, seed = 0"),
]

items = [
    {"kind": "figure", "number": "1", "title": "Cohort overview", "image": "figures/Fig1.png",
     "width_in": 6.3, "claim": "Deaths accrue over variable follow-up → survival analysis is required.",
     "caption_en": "Figure 1. Study cohort (n=299; 96 deaths). (A) Age distribution by outcome. (B) Follow-up time by "
                   "outcome (box = median + IQR; points = patients). Variable follow-up motivates time-to-event analysis.",
     "caption_zh": "图 1。研究队列(n=299;96 例死亡)。(A)年龄分布按结局。(B)随访时间按结局(箱体=中位数+四分位距,"
                   "散点=患者)。随访长短不一,故采用时间-事件分析。",
     "annotations": [("A", "overlaid histograms"), ("B", "box + points"), ("Color", "blue = survived, orange = died")],
     "citation": "Methods/Results, cohort: \"Of 299 patients, 96 (32%) died over a median 115-day follow-up (Fig. 1).\"",
     "repro": "scripts/make_fig1_cohort_overview.py"},

    {"kind": "figure", "number": "2", "title": "Survival by ejection fraction (Kaplan–Meier)", "image": "figures/Fig2.png",
     "width_in": 4.2, "claim": "Patients with reduced ejection fraction have markedly worse survival.",
     "caption_en": "Figure 2. Kaplan–Meier survival by ejection-fraction category — reduced (<30%, n=59), mid (30–45%, "
                   "n=160), preserved (≥45%, n=80) — with 95% bands and numbers at risk/censored/events. Log-rank p<0.001.",
     "caption_zh": "图 2。按射血分数分组的 Kaplan–Meier 生存曲线——降低(<30%,n=59)、中间(30–45%,n=160)、保留"
                   "(≥45%,n=80)——含 95% 置信带及风险/删失/事件数。log-rank p<0.001。",
     "annotations": [("Groups", "clinically defined EF strata"), ("Below plot", "at-risk / censored / events table"),
                     ("Test", "3-group log-rank")],
     "citation": "Results, survival: \"Reduced ejection fraction was associated with lower survival (Fig. 2).\"",
     "repro": "scripts/make_fig2_kaplan_meier.py"},

    {"kind": "figure", "number": "3", "title": "Key predictors by outcome", "image": "figures/Fig3.png",
     "width_in": 6.3, "claim": "The deceased had lower ejection fraction and higher serum creatinine.",
     "caption_en": "Figure 3. The two headline predictors by outcome. (A) Ejection fraction and (B) serum creatinine in "
                   "patients who survived vs died. Box = median + IQR; points = patients. Mann–Whitney U; ***p<0.001.",
     "caption_zh": "图 3。两个核心预测因子按结局。(A)射血分数、(B)血清肌酐,生存者与死亡者对比。箱体=中位数+四分位距,"
                   "散点=患者。Mann–Whitney U;***p<0.001。",
     "annotations": [("Test", "Mann–Whitney U (creatinine right-skewed)"), ("Markers", "***p<0.001")],
     "citation": "Results, univariable: \"EF was lower and creatinine higher among those who died (Fig. 3; Table 1).\"",
     "repro": "scripts/make_fig3_predictors_boxplot.py"},

    {"kind": "figure", "number": "4", "title": "Multivariable Cox model (forest)", "image": "figures/Fig4.png",
     "width_in": 4.5, "claim": "Age, low EF and high creatinine independently raise mortality hazard.",
     "caption_en": "Figure 4. Hazard ratios (95% CI) from a multivariable Cox model (log scale; reference HR=1). "
                   "Continuous predictors standardized (HR per 1 SD); coloured = p<0.05. Age (1.74), creatinine (1.39), "
                   "CPK (1.24), anaemia (1.58), hypertension (1.61) raised hazard; ejection fraction (0.56) lowered it. "
                   "Concordance index = 0.74.",
     "caption_zh": "图 4。多因素 Cox 模型的风险比(95% CI;对数坐标,参考 HR=1)。连续变量标准化(HR 为每 1 SD);彩色为 "
                   "p<0.05。年龄(1.74)、肌酐(1.39)、CPK(1.24)、贫血(1.58)、高血压(1.61)升高风险;射血分数(0.56)"
                   "降低风险。一致性指数=0.74。",
     "annotations": [("Scale", "log-scale HR, reference at 1"), ("Continuous", "standardized → per 1 SD"),
                     ("Highlight", "significant predictors coloured")],
     "citation": "Results, adjusted analysis: \"EF, creatinine and age were independent predictors (Fig. 4; Table 2).\"",
     "repro": "scripts/make_fig4_cox_forest.py"},

    {"kind": "figure", "number": "5", "title": "Correlations among predictors", "image": "figures/Fig5.png",
     "width_in": 4.2, "claim": "Predictors are weakly correlated — little collinearity.",
     "caption_en": "Figure 5. Spearman correlations among continuous variables (diverging colormap centred at ρ=0; ρ "
                   "annotated). Correlations are weak (|ρ|≤0.30), arguing against collinearity in the Cox model.",
     "caption_zh": "图 5。连续变量间的 Spearman 相关(发散色标以 ρ=0 为中心,标注 ρ)。相关普遍较弱(|ρ|≤0.30),"
                   "表明 Cox 模型无明显共线性。",
     "annotations": [("Method", "Spearman (robust to skew)"), ("Colormap", "diverging, centred at 0")],
     "citation": "Results, diagnostics: \"Predictors were weakly correlated, arguing against collinearity (Fig. 5).\"",
     "repro": "scripts/make_fig5_correlation.py"},

    {"kind": "figure", "number": "6", "title": "Two features vs full set (ROC)", "image": "figures/Fig6.png",
     "width_in": 4.2, "claim": "Serum creatinine + ejection fraction predict death almost as well as all features.",
     "caption_en": "Figure 6. ROC for predicting in-study death (logistic regression, 5-fold cross-validated). A "
                   "two-feature model — creatinine + ejection fraction (AUC=0.75) — nearly matched the full model "
                   "(AUC=0.76). Follow-up time excluded to avoid leakage.",
     "caption_zh": "图 6。预测院内死亡的 ROC(Logistic 回归,5 折交叉验证)。仅用肌酐+射血分数(AUC=0.75)几乎与全特征"
                   "模型(AUC=0.76)持平。已排除随访时间以防泄漏。",
     "annotations": [("Validation", "cross-validated AUC, not in-sample"), ("Leakage", "`time` excluded as predictor"),
                     ("Diagonal", "chance line shown")],
     "citation": "Discussion, parsimony: \"Two features reproduced most of the full model's discrimination (Fig. 6).\"",
     "repro": "scripts/make_fig6_roc.py"},

    {"kind": "table", "number": "1", "title": "Baseline characteristics", "csv": "figures/Table1.csv",
     "table_title": "Table 1. Baseline characteristics by survival status.",
     "table_note": "Continuous: median [IQR], Mann–Whitney U; binary: n (%), chi-square. Data: Chicco & Jurman (2020).",
     "claim": "Cohort description and univariable differences.",
     "annotations": [("Continuous", "median [IQR]"), ("Binary", "n (%)"), ("p", "univariable, unadjusted for follow-up")],
     "citation": "Results, opening: \"Baseline characteristics are summarized in Table 1.\"",
     "repro": "scripts/make_table1_baseline.py"},

    {"kind": "table", "number": "2", "title": "Multivariable Cox model", "csv": "figures/Table2.csv",
     "table_title": "Table 2. Multivariable Cox proportional-hazards model for mortality.",
     "table_note": "HR with 95% CI; continuous predictors standardized (per 1 SD). C-index = 0.74; n=299, events=96. "
                   "Data: Chicco & Jurman (2020).",
     "claim": "Exact adjusted hazard ratios behind Fig. 4.",
     "annotations": [("Model", "all covariates jointly"), ("Continuous", "per 1 SD"), ("Fit", "C-index reported")],
     "citation": "Results, adjusted analysis: exact HRs cited alongside Fig. 4.",
     "repro": "scripts/make_table2_cox.py"},
]

out = EXAMPLE_DIR / "Figure_Report.docx"
build_report(out, title="Figure & Table Report / 图表报告",
             subtitle="Heart-failure survival — paper-figures worked example / 心衰生存分析案例",
             meta=meta, items=items, base_dir=str(EXAMPLE_DIR))
print(f"wrote {out}")
