"""Build the stage-7 figure report as a Word document (Figure_Report.docx).

Embeds every figure image and renders the tables inline as three-line tables, with
bilingual captions, annotations, citation locations and reproducibility notes.
"""
from _common import FIGDIR  # noqa: F401  (adds skill scripts to sys.path)
from report_docx import build_report

EXAMPLE_DIR = FIGDIR.parent

meta = [
    ("Source paper / 来源论文", "Gorman, Williams & Fraser (2014), PLOS ONE 9(3):e90081 (CC BY 4.0)"),
    ("Data / 数据", "palmerpenguins (CC0); data/penguins_raw.csv — one row = one penguin"),
    ("Preset / 预设", "generic high-quality (single/double column)"),
    ("Generated by / 生成", "paper-figures skill — matplotlib/seaborn, seed = 0"),
]

items = [
    {"kind": "figure", "number": "1", "title": "Body size among species", "image": "figures/Fig1.png",
     "width_in": 6.3, "claim": "Flipper length and body mass differ among species; Gentoo largest.",
     "caption_en": "Figure 1. Body size differs among penguin species. (A) Flipper length and (B) body mass for "
                   "Adélie (n=151), Chinstrap (n=68) and Gentoo (n=123); birds missing the measurement are excluded. "
                   "Box = median + IQR; points = individual birds. Kruskal–Wallis (A: H=244.9; B: H=217.6; both p<0.001).",
     "caption_zh": "图 1。企鹅体型存在物种差异。(A)鳍长、(B)体重,阿德利(n=151)、帽带(n=68)、巴布亚(n=123);"
                   "缺测个体已剔除。箱体=中位数+四分位距,散点=个体。Kruskal–Wallis(A:H=244.9;B:H=217.6;p 均<0.001)。",
     "annotations": [("Test 检验", "non-parametric Kruskal–Wallis"), ("Spread 离散", "full distribution shown (no error bars)"),
                     ("Color 配色", "Okabe–Ito, colorblind-safe")],
     "citation": "Results, body-size paragraph: \"Gentoo were largest in flipper length and body mass (Fig. 1).\"",
     "repro": "scripts/make_fig1_morphometrics.py"},

    {"kind": "figure", "number": "2", "title": "Sexual size dimorphism", "image": "figures/Fig2.png",
     "width_in": 4.0, "claim": "Within every species, males are heavier than females.",
     "caption_en": "Figure 2. Sexual size dimorphism in body mass. Males (orange) exceed females (blue) within each "
                   "species. Per-species Welch's t-test; ***p<0.001 (Adélie t=13.1, g=2.16; Chinstrap t=5.2, g=1.25; "
                   "Gentoo t=14.8, g=2.68).",
     "caption_zh": "图 2。体重的性体型二态。各物种内雄性(橙)大于雌性(蓝)。各物种 Welch t 检验;***p<0.001"
                   "(阿德利 t=13.1,g=2.16;帽带 t=5.2,g=1.25;巴布亚 t=14.8,g=2.68)。",
     "annotations": [("Test", "Welch's t-test (unequal variance)"), ("Effect size 效应量", "Hedges' g, large in all"),
                     ("Markers", "***p<0.001")],
     "citation": "Results, \"Sexual dimorphism\": \"Males were heavier across all species (Fig. 2; Table 2).\"",
     "repro": "scripts/make_fig2_dimorphism.py"},

    {"kind": "figure", "number": "3", "title": "Culmen shape relationship", "image": "figures/Fig3.png",
     "width_in": 4.0, "claim": "Culmen length and depth are positively related within each species.",
     "caption_en": "Figure 3. Culmen length vs depth with per-species OLS fits and 95% confidence bands. Positive within "
                   "each species, though pooling reverses the slope (Simpson's paradox) — hence species-specific fits.",
     "caption_zh": "图 3。喙长 vs 喙深,按物种分别拟合最小二乘回归及 95% 置信带。各物种内正相关;合并则斜率反转(辛普森悖论),"
                   "故采用分物种拟合。",
     "annotations": [("Axes", "x = culmen length (mm), y = culmen depth (mm)"), ("Band", "95% CI of the fitted mean")],
     "citation": "Results, trait covariation: \"Deeper culmens accompanied longer culmens within species (Fig. 3).\"",
     "repro": "scripts/make_fig3_scatter_regression.py"},

    {"kind": "figure", "number": "4", "title": "Flipper-length distribution (raincloud)", "image": "figures/Fig4.png",
     "width_in": 4.0, "claim": "Flipper-length distributions are well separated across species.",
     "caption_en": "Figure 4. Flipper length by species as a raincloud: half-violin (density), box (median + IQR) and "
                   "jittered points (individuals). Gentoo show clearly longer flippers.",
     "caption_zh": "图 4。各物种鳍长云雨图:半小提琴(密度)、箱体(中位数+四分位距)与抖动散点(个体)。巴布亚鳍长明显更大。",
     "annotations": [("Shows", "density + summary + raw data at once"), ("n", "152 / 68 / 124")],
     "citation": "Results, flipper length: \"Distributions barely overlapped between Gentoo and the others (Fig. 4).\"",
     "repro": "scripts/make_fig4_raincloud.py"},

    {"kind": "figure", "number": "5", "title": "Body-mass distribution", "image": "figures/Fig5.png",
     "width_in": 6.3, "claim": "Gentoo body mass is shifted to higher values.",
     "caption_en": "Figure 5. Body-mass distribution by species. (A) Overlaid histograms (22 bins); (B) empirical CDFs. "
                   "The ECDF shows Gentoo shifted entirely rightward of Adélie and Chinstrap.",
     "caption_zh": "图 5。各物种体重分布。(A)叠加直方图(22 区间);(B)经验累积分布。ECDF 显示巴布亚整体右移于阿德利与帽带。",
     "annotations": [("A", "histogram, bin width stated"), ("B", "ECDF — binning-free, ideal for comparison")],
     "citation": "Results, mass distribution: \"Gentoo body mass scarcely overlapped the other species (Fig. 5).\"",
     "repro": "scripts/make_fig5_distribution.py"},

    {"kind": "figure", "number": "6", "title": "Species across islands", "image": "figures/Fig6.png",
     "width_in": 4.2, "claim": "Species occupy islands unevenly.",
     "caption_en": "Figure 6. Penguins sampled per island and species (counts on bars; bars from zero). Species and "
                   "island are strongly associated (χ²≈300, p<0.001).",
     "caption_zh": "图 6。各岛各物种采样数量(柱顶标注计数,柱从零起)。物种与岛屿强关联(χ²≈300,p<0.001)。",
     "annotations": [("Bars", "counts, baseline at zero"), ("Test", "chi-square of association")],
     "citation": "Methods/Results, sampling: \"Sampling by island and species is shown in Fig. 6 (see Table 3).\"",
     "repro": "scripts/make_fig6_bar_counts.py"},

    {"kind": "figure", "number": "7", "title": "Trait correlations", "image": "figures/Fig7.png",
     "width_in": 4.0, "claim": "Body mass tracks flipper length; culmen depth runs opposite.",
     "caption_en": "Figure 7. Pearson correlations among four morphometric traits. Diverging colormap centred at r=0; "
                   "r annotated. Flipper length and body mass correlate most (r=0.87).",
     "caption_zh": "图 7。四项形态性状的 Pearson 相关。发散色标以 r=0 为中心,标注 r。鳍长与体重相关最强(r=0.87)。",
     "annotations": [("Colormap", "diverging, centred at 0"), ("Cells", "r annotated")],
     "citation": "Results, trait structure: \"Flipper length and body mass were tightly coupled (Fig. 7).\"",
     "repro": "scripts/make_fig7_corr_heatmap.py"},

    {"kind": "figure", "number": "8", "title": "Morphometric space (PCA)", "image": "figures/Fig8.png",
     "width_in": 4.2, "claim": "The four traits separate species in two dimensions.",
     "caption_en": "Figure 8. PCA of four z-scored traits. Points coloured by species; arrows are trait loadings. "
                   "PC1 (69%) separates Gentoo; PC2 (19%) reflects culmen depth.",
     "caption_zh": "图 8。四项标准化性状的主成分分析。散点按物种着色,箭头为载荷。PC1(69%)区分巴布亚;PC2(19%)反映喙深。",
     "annotations": [("Preprocessing", "traits z-scored before PCA"), ("Axes", "% variance explained")],
     "citation": "Results, multivariate: \"A PCA of morphometrics cleanly separated the species (Fig. 8).\"",
     "repro": "scripts/make_fig8_pca.py"},

    {"kind": "figure", "number": "9", "title": "Dimorphism effect sizes (forest)", "image": "figures/Fig9.png",
     "width_in": 5.0, "claim": "The male–female body-mass effect is large in every species.",
     "caption_en": "Figure 9. Standardized male–female body-mass difference (Hedges' g) per species with 95% CIs; "
                   "dashed line at g=0. All intervals lie well above zero (Adélie 2.16; Chinstrap 1.25; Gentoo 2.68).",
     "caption_zh": "图 9。各物种雄减雌体重的标准化差异(Hedges' g)及 95% CI;虚线为 g=0。所有区间均明显大于零"
                   "(阿德利 2.16;帽带 1.25;巴布亚 2.68)。",
     "annotations": [("Point", "g"), ("Line", "95% CI"), ("Reference", "dashed at 0")],
     "citation": "Discussion, effect magnitude: \"Dimorphism was not merely significant but large (Fig. 9).\"",
     "repro": "scripts/make_fig9_forest.py"},

    {"kind": "table", "number": "1", "title": "Morphometric summary", "csv": "figures/Table1.csv",
     "table_title": "Table 1. Morphometric measurements (mean ± SD) by species and sex.",
     "table_note": "n = number of penguins. Data: Gorman et al. (2014).",
     "claim": "Per-group morphometrics for reference.",
     "annotations": [("Statistic", "mean ± SD"), ("n", "stated per group")],
     "citation": "Results, opening: \"Morphometrics by species and sex are summarized in Table 1.\"",
     "repro": "scripts/make_table1_summary.py"},

    {"kind": "table", "number": "2", "title": "Sexual dimorphism tests", "csv": "figures/Table2.csv",
     "table_title": "Table 2. Sexual dimorphism by species and trait (Welch's t-test).",
     "table_note": "Male vs female; g = Hedges' g (positive = males larger). Data: Gorman et al. (2014).",
     "claim": "Exact test statistics behind Fig. 2.",
     "annotations": [("Test", "Welch's t; Welch–Satterthwaite df"), ("Effect", "Hedges' g with 95% CI")],
     "citation": "Results, \"Sexual dimorphism\": cited alongside Fig. 2 for exact statistics.",
     "repro": "scripts/make_table2_dimorphism_stats.py"},

    {"kind": "table", "number": "3", "title": "Sample composition", "csv": "figures/Table3.csv",
     "table_title": "Table 3. Sample composition by species, island and sex (number of penguins).",
     "table_note": "Unknown = sex not determined. Data: Gorman et al. (2014).",
     "claim": "Documents the analysed sample.",
     "annotations": [("Counts", "with row and grand totals")],
     "citation": "Methods, study sample: \"The analysed sample is detailed in Table 3.\"",
     "repro": "scripts/make_table3_composition.py"},
]

out = EXAMPLE_DIR / "Figure_Report.docx"
build_report(out, title="Figure & Table Report / 图表报告",
             subtitle="Antarctic penguin morphometrics — paper-figures worked example / 南极企鹅形态学案例",
             meta=meta, items=items, base_dir=str(EXAMPLE_DIR))
print(f"wrote {out}")
